# Exercise 3

1. create a 3x3 matrix with values ranging from 2 to 10

In [1]:
import numpy as np
matrix = np.linspace(2, 10, 9).reshape(3,3)
matrix

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

In [2]:
np.arange(2, 11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [7]:
matrix = np.arange(2, 11).reshape(3,3)
matrix

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

2. concentenate the following arrays [[0, 1, 3], [5, 7, 9]] and [[0, 2, 4], [6, 8, 10]]

In [9]:
matrix2 = np.array([[0,1,3],
                   [5,7,9]])
matrix3 = np.array([[0,2,4],
                    [6,8,10]])
matrix4 = np.concatenate((matrix2, matrix3), axis = 0)
matrix4

array([[ 0,  1,  3],
       [ 5,  7,  9],
       [ 0,  2,  4],
       [ 6,  8, 10]])

In [5]:
matrix4 = np.concatenate((matrix2, matrix3), axis = 1)
matrix4

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])