# Exercise 2

### 1. Generate a 1-D array containing 5 random integers from 0 to 100

In [6]:
from numpy import random
rand_int= random.randint(1,100, size=5)
rand_int

array([32,  3, 84, 37, 59])

### 2. Generate a 2-D array with 3 rows, each row contains 5 random integers from 0 to 100

In [8]:
rand_int2 = random.randint(0,100, size = (3,5))
rand_int2

array([[79, 26, 85, 59, 71],
       [20, 46, 52,  3, 43],
       [93, 65,  8,  7,  5]])

### 3 . Generate a 1-D array of 30 evenly spaced elements between 1.5 and 5.5, inclusive.

In [12]:
import numpy as np
element = np.linspace(1.5, 5.5, 30)
element

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])