# Shape and Size of an Array

In [ ]:
#ndarray.ndim : the number of axes \ 
#ndarray.size : the total number of element \ 
#ndarray.shape : the number of elements stored along each dimension of the array. 
#If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2,3) 

In [2]:
import numpy as np
from numpy import random

my_array = np.array([[[0, 1, 2, 3],
                      [4, 5, 6, 7]],
                          
                      [[0, 1, 2, 3],
                      [4, 5, 6, 7]],
                         
                      [[0 ,1 ,2, 3],
                      [4, 5, 6, 7]]])
my_array

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [4]:
my_array.ndim

3

In [5]:
my_array.size

24

In [6]:
my_array.shape

(3, 2, 4)

##### Reshaping an array

 When you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [7]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [10]:
a.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
a. reshape (2,3)

array([[0, 1, 2],
       [3, 4, 5]])