### Using Array - Generating Functions


#### Arrange

In [2]:
import numpy as np

# create a range

x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a = []
for i in range(10):
    a.append(i)
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
# create a range

x = np.arange(15, 20)

x


array([15, 16, 17, 18, 19])

In [6]:
# create a range

x = np.arange(10, 20, 2) # 10: di mulai dari angka 10, 20: angka yang d hasilkan sampai 20, 2 adalah kelipatanya

x

array([10, 12, 14, 16, 18])

In [9]:
x = np.arange(-1, 1, 0.1)

x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

#### Linspace

In [20]:
np.linspace(0,3, 6)  # 0: dimulainya angka (start), 3: angka akhir (end), 5 : jumlah total angka yg d hasilkan. 
                    # Linspace akan membagi rata angka2 tersebut

array([0. , 0.6, 1.2, 1.8, 2.4, 3. ])

### Random Data

In [30]:
from numpy import random

In [42]:
s = random.rand(5,5)
s

array([[0.85952154, 0.37746331, 0.51511303, 0.58830459, 0.77516943],
       [0.84275168, 0.66351118, 0.53741776, 0.06499014, 0.15102275],
       [0.36653301, 0.92001049, 0.94777258, 0.77183913, 0.75372809],
       [0.82003998, 0.34700398, 0.57840378, 0.04765596, 0.46005306],
       [0.33439741, 0.66962539, 0.72375067, 0.55671187, 0.39309015]])

In [33]:
x = random.randn(5,5)
x

array([[ 0.68035692,  0.84168215,  0.13078637,  0.0468679 , -0.83568747],
       [ 0.56216518,  1.00784783,  0.88528323, -0.57021604,  1.06397061],
       [-0.28192792,  0.54265369,  0.18384238, -2.22113362, -2.10198422],
       [ 3.10276274, -0.55447233, -0.81885838,  1.44165685, -0.882136  ],
       [-0.90133871,  1.13080969, -2.14115212, -0.08379135, -0.40016071]])

In [34]:
x.dtype

dtype('float64')

In [35]:
x = np.ones(2, dtype = np.int64)
x

array([1, 1], dtype=int64)

In [36]:
random.randint(10)

2

In [37]:
random.randint(2, 10, size=4)

array([6, 7, 8, 6])

In [43]:
random.randint(2, 10, size=(4,2,2))

array([[[4, 5],
        [5, 9]],

       [[7, 5],
        [4, 4]],

       [[7, 7],
        [7, 9]],

       [[8, 7],
        [9, 9]]])