# Indexing and Slicing

In [2]:
import numpy as np
from numpy import random



In [5]:
data = np.array([1, 2, 3, 4, 5])
data[1]

2

In [6]:
data[:3]

array([1, 2, 3])

In [7]:
data[1:]

array([2, 3, 4, 5])

In [8]:
data[-2:]

array([4, 5])

You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you’ll need to subset, slice, and/or index your arrays.

If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.

In [10]:
a = np.array([[1 , 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

You can easily print all of the values in the array that are less than 5.


In [14]:
print(a[a < 5])

[1 2 3 4]


You can also select, for example, numbers that are equal to or greater than 5, and use that condition to index an array.

In [15]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [16]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


Or you can select elements that satisfy two conditions using the & and | operators:

In [18]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [17]:
# pipe, or, vertical bar: |

five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [19]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
a[1,1:3]

array([6, 7])

In [21]:
z = np.array([[[0, 1, 3],
               [5, 7, 9]],
              
              [[0, 2, 4],
               [6, 8, 10]]])
z

array([[[ 0,  1,  3],
        [ 5,  7,  9]],

       [[ 0,  2,  4],
        [ 6,  8, 10]]])

In [22]:
z.shape

(2, 2, 3)

In [25]:
z[0] # access row 0

array([[0, 1, 3],
       [5, 7, 9]])

In [26]:
z[0,1] # access row 0, column 1

array([5, 7, 9])

In [27]:
z[1, 1, 1:] #access row 1, column 1, depth 1-2

array([ 8, 10])

In [28]:
a = np.array([1,3,1,4,5,2,1])
a

array([1, 3, 1, 4, 5, 2, 1])

In [29]:
a[1:4]

array([3, 1, 4])

In [30]:
a

array([1, 3, 1, 4, 5, 2, 1])