# Basic Array Operation

In [7]:
import numpy as np
from numpy import random

In [10]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
print (data)
print(ones)

[1 2]
[1 1]


In [11]:
data + ones

array([2, 3])

In [12]:
data - ones

array([0, 1])

In [13]:
data * data

array([1, 4])

In [14]:
data / data

array([1., 1.])

In [15]:

#a.sum: menjumlahkan seluruh angka yg ada di dalam array
a = np.array([1, 2, 3, 4])

a.sum()

10

sum the rows/columns

In [16]:
# axis = 0 : menjumlahkan antar kolom

b = np.array([[1, 1],
              [2, 2]])
b.sum(axis=0)

array([3, 3])

In [17]:
# axis =1 : menjumlahkan dalam 1 rom

b = np.array([[1, 1],
              [2, 2]])
b.sum(axis=1)

array([2, 4])