### Create Matrix Zeros

In [3]:
import numpy as np

# One dimension

zeros_matrix = np.zeros(5)

zeros_matrix

array([0., 0., 0., 0., 0.])

In [4]:
zeros_matrix.shape

(5,)

In [5]:
# should  be in tuple format

zeros_matrix2 = np.zeros((5,2)) # 5 rows, 2 columns
zeros_matrix2 

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
zeros_matrix2.shape

(5, 2)

### Matrix One

In [7]:
#one dimension

matrix_ones = np.ones(5)
matrix_ones 

array([1., 1., 1., 1., 1.])

In [8]:
#3 dimension

matrix_ones2 = np.ones((3, 4, 2)) #3 rows, 4 columns, 2 depth
matrix_ones2


array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])