# NUMPY - Multidimensional Data Arrays

It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. NumPy brings the computational power of languages like C and Fortran to Python, a language much easier to learn and use.

In [1]:
import numpy as np

In [3]:
np.__version__

'1.20.3'

In [4]:
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x0000017BA6452B80>, toplevel='numpy')>

### What is Array?


In [11]:
# Python List

a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

#### In the numpy package the terminology used for vectors, matrices and higher-dimensional data sets is array.


In [14]:
a_array = np.array(a)
b_array = np.array(b)

print(a_array + b_array)
print(a_array / b_array)

[ 6  8 10 12]
[0.2        0.33333333 0.42857143 0.5       ]


## Creating numpy arrays


There are some ways to initialize new numpy arrays:

a Python list or tuples
using functions that are dedicated to generating numpy arrays, such as arange, linspace, etc.
reading data from files

### Lists


In [15]:
# vector: the argument to the array function is a list
# 1 dimensi

v = np.array([1, 2, 3, 4, 5])

v.shape

(5,)

In [16]:
# matrix: the argument to the array function is a nested list
# 2 dimensi

m = np.array([[1, 2, 3], [4, 5, 6]])

m.shape

(2, 3)

The v and m objects are both of the type ndarray that the numpy module provides.

In [17]:
type(v), type(m)

(numpy.ndarray, numpy.ndarray)

In [18]:
a = [1,2,3]
type(a)

list


The difference between the v and m arrays is only their shapes. We can get information about the shape of an array by using the ndarray.shape property.

In [19]:
v.shape

(5,)

In [21]:
m.shape

(2, 3)

In [22]:
m.size

6

#### numpy.ndarray looks very similiar to the list. So, why not use the list instead? numpay.ndarray is used for several reason:

Lists are very general. They can contain any kind of object. They do not support mathematical functions such as matrix and dot multiplication, etc.
Numpy arrays are statically typed and homogenous. The type of the elements is determined when the array is created
Numpy arrays are memory efficient
It is fast for implementation of mathematical function
We can see the type of data of an array using dtype

In [23]:
one_dimension = np.array([1, 2, 3])
one_dimension

array([1, 2, 3])

In [24]:
one_dimension.shape

(3,)

In [25]:
two_dimension = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

two_dimension

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
two_dimension.shape

(3, 3)

In [27]:
three_dimension = np.array([[[1, 2, 3, 5],
                          [4, 5, 6, 6],
                          [7, 8, 9, 8],
                          [7, 8, 9, 8]],
                         
                         [[1, 2, 3, 8],
                          [4, 5, 6, 8],
                          [7, 8, 9, 8],
                          [7, 8, 9, 8]],
                         
                         [[1, 2, 3, 8],
                          [4, 5, 6, 8],
                          [7, 8, 9, 8],
                          [7, 8, 9, 8]],
                         
                         [[1, 2, 3, 8],
                          [4, 5, 6, 8],
                          [7, 8, 9, 8],
                          [7, 8, 9, 8]]])

# Print hasil
three_dimension

array([[[1, 2, 3, 5],
        [4, 5, 6, 6],
        [7, 8, 9, 8],
        [7, 8, 9, 8]],

       [[1, 2, 3, 8],
        [4, 5, 6, 8],
        [7, 8, 9, 8],
        [7, 8, 9, 8]],

       [[1, 2, 3, 8],
        [4, 5, 6, 8],
        [7, 8, 9, 8],
        [7, 8, 9, 8]],

       [[1, 2, 3, 8],
        [4, 5, 6, 8],
        [7, 8, 9, 8],
        [7, 8, 9, 8]]])

In [28]:
three_dimension.shape

(4, 4, 4)

In [29]:
ones = np.ones((7, 7), dtype=int)

# Print ones
ones

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [30]:
m = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=float)

m

array([[1., 2., 3.],
       [4., 5., 6.]])

Common data types that can be used with dtype are: int, float, complex, bool, object, etc.