# Adding, Removing, Sorting

## Adding / Append

In [2]:
import numpy as np
from numpy import random

In [1]:
a =[]
a

[]

In [2]:
a.append(5)
a

[5]

In [13]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr2=np.append(arr,[13,14])
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 13, 14])

#### When axis is specified, values must have the correct shape.

In [18]:
my_arr1=np.array([[1,2,3],
                [5,7,8]])
my_arr1

array([[1, 2, 3],
       [5, 7, 8]])

In [19]:
my_arr1.shape

(2, 3)

In [44]:
my_arr2=np.append(my_arr1, [[9,5,6]], axis=0)
my_arr2

array([[1, 2, 3],
       [5, 7, 8],
       [9, 5, 6]])

In [3]:
a = np.array([[1, 2, 8], [5, 8, 10]])
b = np.array([[8, 2, 1], [3, 9, 1]])
c = np.concatenate((a, b), axis = 0)
print(c)

[[ 1  2  8]
 [ 5  8 10]
 [ 8  2  1]
 [ 3  9  1]]


In [4]:
a = np.array([[1, 2, 8], [5, 8, 10]])
b = np.array([[8, 2, 1], [3, 9, 1]])
c = np.concatenate((a, b), axis = 1)
print(c)

[[ 1  2  8  8  2  1]
 [ 5  8 10  3  9  1]]


### Sorting 

In [6]:
# sorting berdasarkan urutan - np.sort()

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [7]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

### Concatenate Arrays

In [8]:
#Concatenate arrays

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(a,b)

[1 2 3 4] [5 6 7 8]


In [10]:
np.concatenate ((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x,y), axis=0) #if axis = None / (0), then arrays are flatten before use

array([[1, 2],
       [3, 4],
       [5, 6]])

### delete elements of an array

In [16]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
np.sort(arr)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
np.delete(arr,1,axis=0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])