# Adding, Removing, Sorting

## Adding

In [4]:
import numpy as np
from numpy import random

In [1]:
a =[]
a

[]

In [2]:
a.append(5)
a

[5]

In [13]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr2=np.append(arr,[13,14])
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 13, 14])

In [18]:
my_arr1=np.array([[1,2,3],
                [5,7,8]])
my_arr1

array([[1, 2, 3],
       [5, 7, 8]])

In [19]:
my_arr1.shape

(2, 3)

In [44]:
my_arr2=np.append(my_arr1, [[9,5,6]], axis=0)
my_arr2

array([[1, 2, 3],
       [5, 7, 8],
       [9, 5, 6]])

In [27]:
a=np.array(10)
a

array(10)

In [47]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
a2 = []

In [ ]:
4:6